### ISSUE TITLE
Can not provide publications with page widget.

### ISSUE THREAD

**Issue by Emon-ProCoder7** [wowchemy/starter-academic#128]
I have tried several times to provide publications in the "**publication.md**" and "**featured.md**" file. Also created "**_index.md**" in the "**publication**" folder content repository. but no hope. Kindly provide me some suggestions.

"**Publication.md"** Code

```
+++
widget = "pages"  # See https://sourcethemes.com/academic/docs/page-builder/
headless = true  # This file represents a page section.
active = true  # Activate this widget? true/false
weight = 90  # Order that this section will appear.

title = "Recent Publications"
subtitle = ""

[content]  
  page_type = "publication" 
  count = 0  
  offset = 0
  order = "desc"

 
  [content.filters]
    tag = "Metagenomics"
    category = ""
    publication_type = "Thesis"
    author = "Md. Tabassum Hossain Emon"
    exclude_featured = false
  
[design]
    view = 4
  
[advanced]
 # Custom CSS. 
 css_style = ""
 
 # CSS class.
 css_class = ""
+++
```

"**_index.md**" in "**Publication**" folder

```
---
title: ""
tags: ["Metagenomics"]
authors:
- Md. Tabassum Hossain Emon
date: "2020-09"
doi: ""
publication_types: ["7"]


publication: "*Thesis*(1)"
publication_short: ""

abstract: 

summary: 

featured: true

url_pdf: 
url_code: ''
url_dataset: ''
url_poster: ''
url_project: ''
url_slides: ''
url_source: ''
url_video: ''


image:
  caption: 'Image credit: [**Unsplash**](https://unsplash.com/photos/jdD8gXaTZsc)'
  focal_point: ""
  preview_only: false

slides: example
---

{{% alert note %}}
Click the *Cite* button above to demo the feature to enable visitors to import publication metadata into their reference management software.
{{% /alert %}}

{{% alert note %}}
Click the *Slides* button above to demo Academic's Markdown slides feature.
{{% /alert %}}

Supplementary notes can be added here, including [code and math](https://sourcethemes.com/academic/docs/writing-markdown-latex/).

```
